services:
  - type: web
    name: co2-emission-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py api_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.17
      - key: RENDER
        value: true
    healthCheckPath: /health
    autoDeploy: true 

    